const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const fine=matchMedia('(pointer:fine)').matches;const progress=document.querySelector('.progress');const copy=document.getElementById('copy');const command='cmake --preset dev && cmake --build build/dev && ctest --preset dev';
const polish=document.createElement('link');polish.rel='stylesheet';polish.href='site-polish.css?v=20260909';document.head.appendChild(polish);
addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.transform=`scaleX(${max?scrollY/max:0})`},{passive:true});
if(copy)copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(command);copy.textContent='COPIED';setTimeout(()=>copy.textContent='COPY',1400)}catch{copy.textContent='SELECT'}});
const reveals=document.querySelectorAll('.reveal');if(reduced||!('IntersectionObserver'in window))reveals.forEach(el=>el.classList.add('is-visible'));else{const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.12});reveals.forEach(el=>io.observe(el))}
const links=[...document.querySelectorAll('.site-header nav a')];const sections=links.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);if('IntersectionObserver'in window){const navIO=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`))}),{rootMargin:'-35% 0px -55%'});sections.forEach(s=>navIO.observe(s))}
if(!reduced&&fine){document.documentElement.classList.add('motion-ready');
const art=document.querySelector('.hero-art'),core=document.querySelector('.hero-core'),rings=[...document.querySelectorAll('.hero-ring')],notes=[...document.querySelectorAll('.hero-note')];let mx=.5,my=.5,rx=.5,ry=.5,raf=0;const move=e=>{mx=e.clientX/innerWidth;my=e.clientY/innerHeight;if(!raf)raf=requestAnimationFrame(frame)};const frame=()=>{rx+=(mx-rx)*.075;ry+=(my-ry)*.075;const px=(rx-.5)*2,py=(ry-.5)*2;if(art){art.style.setProperty('--mx',`${rx*100}%`);art.style.setProperty('--my',`${ry*100}%`)}if(core)core.style.transform=`translate3d(${px*24}px,${py*18}px,0) scale(${1+Math.abs(px+py)*.016})`;rings.forEach((r,i)=>{const d=i+1;r.style.transform=`translate3d(${px*d*9}px,${py*d*7}px,0) rotate(${[-18,63,0][i]}deg) scaleY(${[.46,.35,1][i]})`});notes.forEach((n,i)=>n.style.transform=`translate3d(${px*(i+1)*7}px,${py*(i+1)*5}px,0)`);raf=0};addEventListener('pointermove',move,{passive:true});addEventListener('pointerleave',()=>{mx=my=.5});
const spotlight=document.createElement('span');spotlight.className='cursor-light';document.body.appendChild(spotlight);let lx=innerWidth/2,ly=innerHeight/2;addEventListener('pointermove',e=>{lx=e.clientX;ly=e.clientY;document.documentElement.style.setProperty('--cursor-x',`${lx}px`);document.documentElement.style.setProperty('--cursor-y',`${ly}px`);spotlight.style.left=`${lx}px`;spotlight.style.top=`${ly}px`},{passive:true});
const magnetic=[...document.querySelectorAll('.button,.header-cta,.doc-links a')];magnetic.forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/r.width,y=(e.clientY-r.top-r.height/2)/r.height;el.style.setProperty('--mx',`${x*13}px`);el.style.setProperty('--my',`${y*9}px`);el.classList.add('pointer-hot')});el.addEventListener('pointerleave',()=>{el.style.setProperty('--mx','0px');el.style.setProperty('--my','0px');el.classList.remove('pointer-hot')})});
const nodes=[...document.querySelectorAll('.arch-node')];nodes.forEach(node=>node.addEventListener('pointermove',e=>{const r=node.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;node.style.setProperty('--rx',`${-y*7}deg`);node.style.setProperty('--ry',`${x*8}deg`);node.style.setProperty('--mx',`${x*8}px`);node.style.setProperty('--my',`${y*8}px`);node.classList.add('pointer-hot')}));nodes.forEach(node=>node.addEventListener('pointerleave',()=>{node.style.setProperty('--rx','0deg');node.style.setProperty('--ry','0deg');node.style.setProperty('--mx','0px');node.style.setProperty('--my','0px');node.classList.remove('pointer-hot')}));
const trail=[];for(let i=0;i<9;i++){const s=document.createElement('i');s.className='pointer-trail';document.body.appendChild(s);trail.push({el:s,x:innerWidth/2,y:innerHeight/2})}addEventListener('pointermove',e=>{let x=e.clientX,y=e.clientY;trail.forEach((p,i)=>{p.x+=(x-p.x)*(0.28-i*.018);p.y+=(y-p.y)*(0.28-i*.018);p.el.style.left=`${p.x}px`;p.el.style.top=`${p.y}px`;p.el.style.opacity=`${(9-i)/16}`})},{passive:true});
const ripple=e=>{const r=document.createElement('span');r.className='click-ripple';r.style.left=`${e.clientX}px`;r.style.top=`${e.clientY}px`;document.body.appendChild(r);requestAnimationFrame(()=>r.classList.add('explode'));setTimeout(()=>r.remove(),650)};addEventListener('click',ripple,{passive:true});
const textSelectors='h1,h2,h3,p,.eyebrow,.section-kicker,.hero-note,.hero-data strong,.row-metric strong,.asset-spec strong,.graph-mark b,.build-box code,.terminal-body p,.doc-links a,.site-header nav a,.brand span,.site-footer span';const textEls=[...document.querySelectorAll(textSelectors)].filter(el=>el.children.length===0&&el.textContent.trim().length>1);textEls.forEach(el=>{const text=el.textContent;const frag=document.createDocumentFragment();[...text].forEach((ch,i)=>{const s=document.createElement('span');s.className='water-char';s.textContent=ch===' '? '\u00a0':ch;s.dataset.i=i;frag.appendChild(s)});el.textContent='';el.classList.add('water-text');el.appendChild(frag)});
const waterTargets=textEls;let waterX=-9999,waterY=-9999,waterActive=false;const updateWater=e=>{waterX=e.clientX;waterY=e.clientY;waterActive=true;waterTargets.forEach(el=>{const r=el.getBoundingClientRect();if(e.clientX>=r.left-80&&e.clientX<=r.right+80&&e.clientY>=r.top-55&&e.clientY<=r.bottom+55)el.classList.add('wave-active');else el.classList.remove('wave-active')})};addEventListener('pointermove',updateWater,{passive:true});
const waveFrame=()=>{if(waterActive){waterTargets.forEach(el=>{if(!el.classList.contains('wave-active'))return;const r=el.getBoundingClientRect();const cx=waterX-r.left;[...el.children].forEach((ch,i)=>{const cr=ch.offsetLeft+ch.offsetWidth/2;const dist=Math.abs(cr-cx);const amp=Math.max(0,1-dist/115);const phase=(waterX*0.018)+i*.38;ch.style.setProperty('--wy',`${Math.sin(phase)*amp*5}px`);ch.style.setProperty('--wx',`${(cx-cr)*amp*.055}px`);ch.style.setProperty('--wr',`${Math.sin(phase*.8)*amp*1.8}deg`);ch.style.setProperty('--blur',`${amp*.45}px`)})})}requestAnimationFrame(waveFrame)};requestAnimationFrame(waveFrame);
waterTargets.forEach(el=>el.addEventListener('pointerdown',e=>{const r=el.getBoundingClientRect();const x=e.clientX-r.left,y=e.clientY-r.top;const ring=document.createElement('span');ring.className='water-ripple';ring.style.left=`${x}px`;ring.style.top=`${y}px`;el.appendChild(ring);setTimeout(()=>ring.remove(),950)}));
}