const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const fine=matchMedia('(pointer:fine)').matches;const progress=document.querySelector('.progress');const copy=document.getElementById('copy');const command='cmake --preset dev && cmake --build build/dev && ctest --preset dev';
const polish=document.createElement('link');polish.rel='stylesheet';polish.href='site-polish.css';document.head.appendChild(polish);
addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.transform=`scaleX(${max?scrollY/max:0})`},{passive:true});
if(copy)copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(command);copy.textContent='COPIED';setTimeout(()=>copy.textContent='COPY',1400)}catch{copy.textContent='SELECT'}});
const reveals=document.querySelectorAll('.reveal');if(reduced||!('IntersectionObserver'in window))reveals.forEach(el=>el.classList.add('is-visible'));else{const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.12});reveals.forEach(el=>io.observe(el))}
const links=[...document.querySelectorAll('.site-header nav a')];const sections=links.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);if('IntersectionObserver'in window){const navIO=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`))}),{rootMargin:'-35% 0px -55%'});sections.forEach(s=>navIO.observe(s))}
if(!reduced&&fine){const root=document.documentElement;const art=document.querySelector('.hero-art');const core=document.querySelector('.hero-core');const rings=[...document.querySelectorAll('.hero-ring')];const notes=[...document.querySelectorAll('.hero-note')];let mx=.5,my=.5,rx=.5,ry=.5,raf=0;const move=e=>{mx=e.clientX/innerWidth;my=e.clientY/innerHeight;if(!raf)raf=requestAnimationFrame(frame)};const frame=()=>{rx+=(mx-rx)*.055;ry+=(my-ry)*.055;const px=(rx-.5)*2,py=(ry-.5)*2;if(art)art.style.setProperty('--mx',`${rx*100}%`),art.style.setProperty('--my',`${ry*100}%`);if(core)core.style.transform=`translate3d(${px*12}px,${py*9}px,0) scale(${1+Math.abs(px+py)*.008})`;rings.forEach((r,i)=>{const d=i+1;r.style.transform=`translate3d(${px*d*4}px,${py*d*3}px,0) rotate(${[-18,63,0][i]}deg) scaleY(${[.46,.35,1][i]})`});notes.forEach((n,i)=>n.style.transform=`translate3d(${px*(i+1)*3}px,${py*(i+1)*2}px,0)`);raf=0};addEventListener('pointermove',move,{passive:true});addEventListener('pointerleave',()=>{mx=my=.5});if(art){const spotlight=document.createElement('span');spotlight.className='cursor-light';art.appendChild(spotlight);art.addEventListener('pointermove',e=>{const r=art.getBoundingClientRect();spotlight.style.left=`${e.clientX-r.left}px`;spotlight.style.top=`${e.clientY-r.top}px`},{passive:true})}
const magnetic=[...document.querySelectorAll('.button,.header-cta,.doc-links a')];magnetic.forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left-r.width/2)/r.width;const y=(e.clientY-r.top-r.height/2)/r.height;el.style.setProperty('--mx',`${x*9}px`);el.style.setProperty('--my',`${y*7}px`)});el.addEventListener('pointerleave',()=>{el.style.setProperty('--mx','0px');el.style.setProperty('--my','0px')})});
const nodes=[...document.querySelectorAll('.arch-node')];nodes.forEach(node=>node.addEventListener('pointermove',e=>{const r=node.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;node.style.setProperty('--rx',`${-y*4}deg`);node.style.setProperty('--ry',`${x*5}deg`);node.style.setProperty('--mx',`${x*5}px`);node.style.setProperty('--my',`${y*5}px`)}));nodes.forEach(node=>node.addEventListener('pointerleave',()=>{node.style.setProperty('--rx','0deg');node.style.setProperty('--ry','0deg');node.style.setProperty('--mx','0px');node.style.setProperty('--my','0px')}));
}