/// \file
/// Tests for the ASERT difficulty-retargeting rule.
///
/// The expected values below were produced by an independent reference
/// implementation of the specification, which shares no code with
/// `src/consensus/asert.cpp`; agreement between the two is the whole of what a
/// vector test can claim. The property tests around them pin the semantics that
/// the vectors sample: on-schedule chains keep the genesis difficulty,
/// ahead-of-schedule chains get harder, and the target is clamped into
/// `[1, pow_limit]`.

#include <amarian/consensus/asert.hpp>
#include <amarian/consensus/params.hpp>
#include <amarian/consensus/target.hpp>
#include <amarian/consensus/work.hpp>

#include <gtest/gtest.h>

#include <cstdint>
#include <cstddef>
#include <limits>
#include <optional>
#include <vector>

namespace amarian {
namespace {

constexpr int64_t GENESIS_TIME = GENESIS_TIMESTAMP;
constexpr uint32_t MAIN_FLOOR = POW_LIMIT_BITS;

/// One reference row: the scalar rule inputs and the bits an independent
/// implementation of the specification computes for them.
struct Vector {
    int64_t height;
    int64_t tip_time;
    uint32_t expected_bits;
};

// Reference values generated by build/_scratch/asert_vectors.py (kept with the
// decision record). Mainnet constants: 300 s spacing, 172 800 s half-life,
// genesis bits == floor == 0x1d00ffff. Rows 4, 5, 9 and 11 pin the clamp and
// sign behaviour that an implementation most easily gets wrong.
const std::vector<Vector>& MainnetVectors() {
    static const std::vector<Vector> vectors{
        // On schedule, at three very different heights: difficulty unchanged.
        {1, GENESIS_TIME + 1 * 300, 0x1D00FFFFU},
        {576, GENESIS_TIME + 576 * 300, 0x1D00FFFFU},
        {100000, GENESIS_TIME + 100000 * 300, 0x1D00FFFFU},
        // Two days ahead of schedule at height 576 (one half-life): target halves.
        {576, GENESIS_TIME + 576 * 300 - 172800, 0x1C7FFF80U},
        // Two days behind schedule: the doubled target clamps to the floor.
        {576, GENESIS_TIME + 576 * 300 + 172800, 0x1D00FFFFU},
        // One day ahead: an intermediate, unclamped step.
        {576, GENESIS_TIME + 576 * 300 - 86400, 0x1D00B500U},
        // Sub-precision deviation (below 172800/65536 s) leaves the target alone.
        {288, GENESIS_TIME + 288 * 300 - 2, 0x1D00FFFFU},
        // A chain absurdly far behind schedule sits at the floor.
        {1000, GENESIS_TIME + 1000 * 300 + 1000000000000LL, 0x1D00FFFFU},
        // A chain absurdly far ahead of schedule reaches the hardest valid target.
        {1000, GENESIS_TIME + 1000 * 300 - 1000000000000LL, 0x01010000U},
        // A tall, realistically fast chain (30 days ahead at height 2 000 000).
        {2000000, GENESIS_TIME + 2000000 * 300 - 3600LL * 24 * 30, 0x1B01FFFEU},
    };
    return vectors;
}

TEST(Asert, MatchesTheIndependentReferenceVectors) {
    for (const Vector& vector : MainnetVectors()) {
        const uint32_t bits = consensus::AsertNextBits(
            MAIN_FLOOR, GENESIS_TIME, vector.height, vector.tip_time, 300, 172800,
            MAIN_FLOOR);
        EXPECT_EQ(bits, vector.expected_bits)
            << "height " << vector.height << " tip_time " << vector.tip_time;
    }
}

TEST(Asert, AnAnchorHighInAWordSurvivesTheFractionalMultiply) {
    // The fractional step multiplies the anchor target, held as 64-bit limbs, by a
    // factor below 2^17. Whether any limb of that product overflows depends entirely
    // on where the anchor's three mantissa bytes happen to sit inside a limb, and for
    // the floor every shipped network uses they sit low enough that none ever does.
    // An anchor at byte exponent 0x18 puts them at bits 40..55, so the product does
    // overflow and the carry into the next limb is exercised.
    //
    // The expected value is not a second computation of the rule: the same deviation
    // against the 0x1d00ffff anchor is pinned at 0x1d00b500 by the reference vector
    // above, and the two anchors differ by exactly 2^40 — a factor the rule applies
    // as a shift, losing nothing, because the multiply happens far above bit 17. So
    // the mantissa must be the same and only the byte exponent may move.
    constexpr uint32_t HIGH_ANCHOR = 0x1800FFFFU;
    const uint32_t bits = consensus::AsertNextBits(
        HIGH_ANCHOR, GENESIS_TIME, 576, GENESIS_TIME + 576 * 300 - 86400, 300, 172800,
        MAIN_FLOOR);
    EXPECT_EQ(bits, 0x1800B500U);
}

TEST(Asert, TestnetHalfLifeVectors) {
    // Testnet: 3 600 s half-life. Two hours ahead of schedule is exponent -2, i.e.
    // difficulty x4 (target /4); two hours behind clamps to the floor.
    const uint32_t bits_ahead = consensus::AsertNextBits(
        MAIN_FLOOR, GENESIS_TIME, 600, GENESIS_TIME + 600 * 300 - 7200, 300, 3600,
        MAIN_FLOOR);
    EXPECT_EQ(bits_ahead, 0x1C3FFFC0U);

    const uint32_t bits_behind = consensus::AsertNextBits(
        MAIN_FLOOR, GENESIS_TIME, 600, GENESIS_TIME + 600 * 300 + 7200, 300, 3600,
        MAIN_FLOOR);
    EXPECT_EQ(bits_behind, 0x1D00FFFFU);
}

TEST(Asert, TheParamsOverloadIsTheGenesisAnchoredRule) {
    // For every network, the params-bound call must equal the scalar rule fed the
    // network's own genesis anchor and constants.
    const ChainParams* networks[] = {&MAINNET_PARAMS, &TESTNET_PARAMS, &REGTEST_PARAMS};
    for (const ChainParams* params : networks) {
        for (const int64_t height : {1LL, 576LL, 100000LL, 2000000LL}) {
            const int64_t tip_time = params->genesis_timestamp + height * 300 - 5000;
            EXPECT_EQ(consensus::AsertNextBits(*params, static_cast<uint32_t>(height),
                                               tip_time),
                      consensus::AsertNextBits(
                          params->genesis_bits, params->genesis_timestamp, height,
                          tip_time, params->target_block_seconds,
                          params->asert_half_life_seconds, params->pow_limit_bits));
        }
    }
}

TEST(Asert, AnOnScheduleChainKeepsTheGenesisTarget) {
    // The defining property of the genesis-anchored schedule: a tip exactly where an
    // on-schedule chain would be faces exactly the genesis difficulty, at any height.
    for (const int64_t height : {1LL, 288LL, 576LL, 100000LL, 18795000LL}) {
        const int64_t tip_time = GENESIS_TIME + height * 300;
        const uint32_t bits =
            consensus::AsertNextBits(MAIN_FLOOR, GENESIS_TIME, height, tip_time, 300,
                                     172800, MAIN_FLOOR);
        EXPECT_EQ(bits, MAIN_FLOOR) << "height " << height;
    }
}

TEST(Asert, AheadOfScheduleIsHarderAndBehindIsEasier) {
    // The direction of the rule: moving the same height's timestamp earlier (chain
    // ahead of schedule) must never make the target easier, and moving it later must
    // never make it harder. Work is compared rather than compact encodings.
    constexpr int64_t height = 200000;
    const int64_t on_time = GENESIS_TIME + height * 300;
    const uint32_t baseline =
        consensus::AsertNextBits(MAIN_FLOOR, GENESIS_TIME, height, on_time, 300, 172800,
                                 MAIN_FLOOR);
    const Work baseline_work = Work::OfCompactTarget(baseline);

    for (const int64_t ahead : {3600LL, 86400LL, 172800LL, 1728000LL}) {
        const uint32_t bits = consensus::AsertNextBits(
            MAIN_FLOOR, GENESIS_TIME, height, on_time - ahead, 300, 172800, MAIN_FLOOR);
        EXPECT_GE(Work::OfCompactTarget(bits), baseline_work)
            << "ahead by " << ahead << " s";
    }

    for (const int64_t behind : {3600LL, 86400LL, 172800LL}) {
        const uint32_t bits = consensus::AsertNextBits(
            MAIN_FLOOR, GENESIS_TIME, height, on_time + behind, 300, 172800, MAIN_FLOOR);
        EXPECT_LE(Work::OfCompactTarget(bits), baseline_work)
            << "behind by " << behind << " s";
    }
}

TEST(Asert, TheResultIsAlwaysACanonicalEncodingAtOrBelowTheFloor) {
    const auto floor = CompactToTarget(MAIN_FLOOR);
    ASSERT_TRUE(floor.has_value());
    for (const int64_t height : {1LL, 500LL, 18795000LL}) {
        for (const int64_t offset :
             {-1000000000000LL, -172800LL, -300LL, -2LL, 0LL, 2LL, 300LL, 172800LL,
              1000000000000LL}) {
            const int64_t tip_time = GENESIS_TIME + height * 300 + offset;
            const uint32_t bits =
                consensus::AsertNextBits(MAIN_FLOOR, GENESIS_TIME, height, tip_time, 300,
                                         172800, MAIN_FLOOR);
            const auto decoded = CompactToTarget(bits);
            ASSERT_TRUE(decoded.has_value())
                << "height " << height << " offset " << offset;
            EXPECT_LE(*decoded, *floor)
                << "height " << height << " offset " << offset;
        }
    }
}

TEST(Asert, TheRuleIsTotalForAdversarialInputs) {
    // Arbitrary int64 values, including values whose intermediates would overflow
    // naive arithmetic, must produce a canonical answer and never crash or trap.
    constexpr int64_t extremes[] = {
        std::numeric_limits<int64_t>::min(), std::numeric_limits<int64_t>::max(),
        -1, 0, 1, 2, 1000000000000LL, -1000000000000LL};
    for (const int64_t height : extremes) {
        for (const int64_t time : extremes) {
            const uint32_t bits =
                consensus::AsertNextBits(MAIN_FLOOR, GENESIS_TIME, height, time, 300,
                                         172800, MAIN_FLOOR);
            EXPECT_TRUE(CompactToTarget(bits).has_value());
        }
    }
}

}  // namespace
}  // namespace amarian
